"""Milestone 2 Expansion

Revision ID: 23506f28dc89
Revises: 5f4f3bdfd20b
Create Date: 2026-07-22 23:27:38.935966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23506f28dc89"
down_revision: Union[str, None] = "5f4f3bdfd20b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM("RESERVED", "PUBLISHED", "REJECTED", name="cvestate").create(
        op.get_bind()
    )
    postgresql.ENUM("PENDING", "SUCCESS", "FAILED", name="processingstatus").create(
        op.get_bind()
    )
    postgresql.ENUM("NONE", "REQUIRED", name="kevrequirement").create(op.get_bind())
    op.execute("ALTER TYPE alertaction ADD VALUE IF NOT EXISTS 'IN_APP_NOTIFICATION'")
    op.execute("ALTER TYPE alertaction ADD VALUE IF NOT EXISTS 'WEBHOOK'")
    op.create_table(
        "connector_sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                name="syncstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "attempt_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("success_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checkpoint_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_sync_runs_connector_id"),
        "connector_sync_runs",
        ["connector_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "EXPLOIT", "PATCH", "ADVISORY", "UNKNOWN", name="referencecategory"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vulnerability_id", "url", name="uq_vuln_reference"),
    )
    op.create_index(
        op.f("ix_vulnerability_references_vulnerability_id"),
        "vulnerability_references",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_endpoints_user_id"),
        "webhook_endpoints",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_cvss",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=True),
        sa.Column(
            "version",
            sa.Enum("V2", "V3_0", "V3_1", "V4", name="cvssversion"),
            nullable=False,
        ),
        sa.Column("score", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("vector", sa.String(length=128), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="cvssseverity"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 0.0 AND score <= 10.0", name="chk_cvss_score_range"
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["vulnerability_source_records.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerability_cvss_source_record_id"),
        "vulnerability_cvss",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_cvss_vulnerability_id"),
        "vulnerability_cvss",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "watchlist_cwes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("cwe_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cwe_id"], ["cwes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "cwe_id", name="uq_watchlist_cwe_id"),
    )
    op.create_index(
        op.f("ix_watchlist_cwes_cwe_id"), "watchlist_cwes", ["cwe_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_cwes_watchlist_id"),
        "watchlist_cwes",
        ["watchlist_id"],
        unique=False,
    )
    op.create_table(
        "watchlist_keywords",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "keyword", name="uq_watchlist_keyword"),
    )
    op.create_index(
        op.f("ix_watchlist_keywords_watchlist_id"),
        "watchlist_keywords",
        ["watchlist_id"],
        unique=False,
    )
    op.drop_index("ix_connector_states_connector_name", table_name="connector_states")
    op.drop_table("connector_states")
    op.add_column(
        "alert_events",
        sa.Column("deduplication_key", sa.String(length=128), nullable=False),
    )
    op.create_unique_constraint(None, "alert_events", ["deduplication_key"])
    op.add_column(
        "alert_rules", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column("alert_rules", sa.Column("enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "alert_rules", sa.Column("rule_version", sa.Integer(), nullable=False)
    )
    op.add_column(
        "alert_rules",
        sa.Column("epss_condition", sa.Numeric(precision=10, scale=5), nullable=True),
    )
    op.add_column(
        "alert_rules", sa.Column("kev_condition", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "cwe_condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "keyword_condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "trigger_events",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.drop_constraint(
        "alert_rules_watchlist_id_fkey", "alert_rules", type_="foreignkey"
    )
    op.create_unique_constraint(
        "uq_watchlist_id_user_id", "watchlists", ["id", "user_id"]
    )
    op.create_foreign_key(
        None,
        "alert_rules",
        "watchlists",
        ["watchlist_id", "user_id"],
        ["id", "user_id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("webhook_endpoint_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("attempt_count", sa.Integer(), nullable=False),
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("is_terminal", sa.Boolean(), nullable=False),
    )
    op.create_index(
        op.f("ix_notification_deliveries_webhook_endpoint_id"),
        "notification_deliveries",
        ["webhook_endpoint_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_delivery_idempotency_key",
        "notification_deliveries",
        ["idempotency_key"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_foreign_key(
        None,
        "notification_deliveries",
        "webhook_endpoints",
        ["webhook_endpoint_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("uq_product_version_range", "version_ranges", type_="unique")
    op.create_unique_constraint(
        "uq_product_version_range",
        "version_ranges",
        [
            "product_id",
            "version_start",
            "version_start_including",
            "version_end",
            "version_end_including",
        ],
        postgresql_nulls_not_distinct=True,
    )
    op.add_column("vulnerabilities", sa.Column("title", sa.String(), nullable=True))
    op.add_column(
        "vulnerabilities",
        sa.Column(
            "cve_state",
            sa.Enum("RESERVED", "PUBLISHED", "REJECTED", name="cvestate"),
            nullable=True,
        ),
    )
    op.add_column(
        "vulnerabilities",
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "vulnerabilities",
        sa.Column("epss_score", sa.Numeric(precision=10, scale=5), nullable=True),
    )
    op.add_column(
        "vulnerabilities",
        sa.Column("epss_percentile", sa.Numeric(precision=10, scale=5), nullable=True),
    )
    op.add_column(
        "vulnerabilities", sa.Column("kev_required_action", sa.String(), nullable=True)
    )
    op.add_column(
        "vulnerabilities",
        sa.Column("kev_due_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "vulnerabilities",
        sa.Column("ransomware_campaign_use", sa.String(), nullable=True),
    )
    op.drop_column("vulnerabilities", "cvss_v3_vector")
    op.drop_column("vulnerabilities", "cvss_v3_score")
    op.drop_constraint(
        "uq_vuln_product_version", "vulnerability_products", type_="unique"
    )
    op.create_unique_constraint(
        "uq_vuln_product_version",
        "vulnerability_products",
        ["vulnerability_id", "product_id", "version_range_id"],
        postgresql_nulls_not_distinct=True,
    )
    op.add_column(
        "vulnerability_provenance",
        sa.Column("selection_reason", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("external_record_id", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("source_url", sa.String(length=2048), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("normalization_version", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column(
            "processing_status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", name="processingstatus"),
            nullable=False,
        ),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("processing_error", sa.String(), nullable=True),
    )
    op.add_column(
        "vulnerability_source_records",
        sa.Column("is_current", sa.Boolean(), nullable=False),
    )
    op.add_column("watchlists", sa.Column("enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "watchlists",
        sa.Column("min_cvss", sa.Numeric(precision=4, scale=1), nullable=True),
    )
    op.add_column(
        "watchlists",
        sa.Column("min_epss", sa.Numeric(precision=10, scale=5), nullable=True),
    )
    op.add_column(
        "watchlists",
        sa.Column(
            "kev_requirement",
            sa.Enum("NONE", "REQUIRED", name="kevrequirement"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlists", "kev_requirement")
    op.drop_column("watchlists", "min_epss")
    op.drop_column("watchlists", "min_cvss")
    op.drop_column("watchlists", "enabled")
    op.drop_column("vulnerability_source_records", "is_current")
    op.drop_column("vulnerability_source_records", "processing_error")
    op.drop_column("vulnerability_source_records", "processing_status")
    op.drop_column("vulnerability_source_records", "normalization_version")
    op.drop_column("vulnerability_source_records", "source_modified_at")
    op.drop_column("vulnerability_source_records", "source_published_at")
    op.drop_column("vulnerability_source_records", "retrieved_at")
    op.drop_column("vulnerability_source_records", "source_url")
    op.drop_column("vulnerability_source_records", "external_record_id")
    op.drop_column("vulnerability_provenance", "selection_reason")
    op.drop_constraint(
        "uq_vuln_product_version", "vulnerability_products", type_="unique"
    )
    op.create_unique_constraint(
        "uq_vuln_product_version",
        "vulnerability_products",
        ["vulnerability_id", "product_id", "version_range_id"],
    )
    op.add_column(
        "vulnerabilities",
        sa.Column(
            "cvss_v3_score",
            sa.NUMERIC(precision=4, scale=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "vulnerabilities",
        sa.Column(
            "cvss_v3_vector", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("vulnerabilities", "ransomware_campaign_use")
    op.drop_column("vulnerabilities", "kev_due_date")
    op.drop_column("vulnerabilities", "kev_required_action")
    op.drop_column("vulnerabilities", "epss_percentile")
    op.drop_column("vulnerabilities", "epss_score")
    op.drop_column("vulnerabilities", "modified_at")
    op.drop_column("vulnerabilities", "cve_state")
    op.drop_column("vulnerabilities", "title")
    op.drop_constraint("uq_product_version_range", "version_ranges", type_="unique")
    op.create_unique_constraint(
        "uq_product_version_range",
        "version_ranges",
        [
            "product_id",
            "version_start",
            "version_start_including",
            "version_end",
            "version_end_including",
        ],
    )
    op.drop_constraint(
        "notification_deliveries_webhook_endpoint_id_fkey",
        "notification_deliveries",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_delivery_idempotency_key", "notification_deliveries", type_="unique"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_webhook_endpoint_id"),
        table_name="notification_deliveries",
    )
    op.drop_column("notification_deliveries", "is_terminal")
    op.drop_column("notification_deliveries", "idempotency_key")
    op.drop_column("notification_deliveries", "next_retry_at")
    op.drop_column("notification_deliveries", "attempt_count")
    op.drop_column("notification_deliveries", "webhook_endpoint_id")
    op.drop_constraint(
        "alert_rules_watchlist_id_user_id_fkey", "alert_rules", type_="foreignkey"
    )
    op.create_foreign_key(
        "alert_rules_watchlist_id_fkey",
        "alert_rules",
        "watchlists",
        ["watchlist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_watchlist_id_user_id", "watchlists", type_="unique")
    op.drop_column("alert_rules", "trigger_events")
    op.drop_column("alert_rules", "keyword_condition")
    op.drop_column("alert_rules", "cwe_condition")
    op.drop_column("alert_rules", "kev_condition")
    op.drop_column("alert_rules", "epss_condition")
    op.drop_column("alert_rules", "rule_version")
    op.drop_column("alert_rules", "enabled")
    op.drop_column("alert_rules", "name")
    op.drop_constraint(
        "alert_events_deduplication_key_key", "alert_events", type_="unique"
    )
    op.drop_column("alert_events", "deduplication_key")
    op.create_table(
        "connector_states",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "connector_name",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_successful_run",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("cursor", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="connector_states_pkey"),
    )
    op.create_index(
        "ix_connector_states_connector_name",
        "connector_states",
        ["connector_name"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_watchlist_keywords_watchlist_id"), table_name="watchlist_keywords"
    )
    op.drop_table("watchlist_keywords")
    op.drop_index(op.f("ix_watchlist_cwes_watchlist_id"), table_name="watchlist_cwes")
    op.drop_index(op.f("ix_watchlist_cwes_cwe_id"), table_name="watchlist_cwes")
    op.drop_table("watchlist_cwes")
    op.drop_index(
        op.f("ix_vulnerability_cvss_vulnerability_id"), table_name="vulnerability_cvss"
    )
    op.drop_index(
        op.f("ix_vulnerability_cvss_source_record_id"), table_name="vulnerability_cvss"
    )
    op.drop_table("vulnerability_cvss")
    op.drop_index(op.f("ix_webhook_endpoints_user_id"), table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index(
        op.f("ix_vulnerability_references_vulnerability_id"),
        table_name="vulnerability_references",
    )
    op.drop_table("vulnerability_references")
    op.drop_index(
        op.f("ix_connector_sync_runs_connector_id"), table_name="connector_sync_runs"
    )
    op.drop_table("connector_sync_runs")
    op.execute("DROP TYPE IF EXISTS syncstatus")
    op.execute("DROP TYPE IF EXISTS referencecategory")
    op.execute("DROP TYPE IF EXISTS cvssversion")
    op.execute("DROP TYPE IF EXISTS cvssseverity")
    op.execute("DROP TYPE IF EXISTS cvestate")
    op.execute("DROP TYPE IF EXISTS processingstatus")
    op.execute("DROP TYPE IF EXISTS kevrequirement")
    # ### end Alembic commands ###
