"""Milestone 2 models

Revision ID: 5f4f3bdfd20b
Revises: 0001_initial_users
Create Date: 2026-07-22 22:39:00.761725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f4f3bdfd20b"
down_revision: Union[str, None] = "0001_initial_users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_name", sa.String(length=128), nullable=False),
        sa.Column("last_successful_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_states_connector_name"),
        "connector_states",
        ["connector_name"],
        unique=True,
    )
    op.create_table(
        "cwes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cwe_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cwes_cwe_id"), "cwes", ["cwe_id"], unique=True)
    op.create_table(
        "vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=True)
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("cvss_v3_score", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("cvss_v3_vector", sa.String(length=128), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cvss_v3_score >= 0.0 AND cvss_v3_score <= 10.0",
            name="chk_cvss_v3_score_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerabilities_cve_id"), "vulnerabilities", ["cve_id"], unique=True
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_id", "name", name="uq_vendor_product"),
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(
        op.f("ix_products_vendor_id"), "products", ["vendor_id"], unique=False
    )
    op.create_table(
        "vulnerability_cwes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("cwe_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cwe_id"], ["cwes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vulnerability_id", "cwe_id", name="uq_vuln_cwe"),
    )
    op.create_index(
        op.f("ix_vulnerability_cwes_cwe_id"),
        "vulnerability_cwes",
        ["cwe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_cwes_vulnerability_id"),
        "vulnerability_cwes",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_source_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vulnerability_id",
            "source_name",
            "content_hash",
            name="uq_vuln_source_hash",
        ),
    )
    op.create_index(
        op.f("ix_vulnerability_source_records_vulnerability_id"),
        "vulnerability_source_records",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_watchlist_name"),
    )
    op.create_index(
        op.f("ix_watchlists_user_id"), "watchlists", ["user_id"], unique=False
    )
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("cvss_threshold", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column(
            "action", sa.Enum("EMAIL", "WEBHOOK", name="alertaction"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cvss_threshold >= 0.0 AND cvss_threshold <= 10.0",
            name="chk_rule_cvss_threshold",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_rules_user_id"), "alert_rules", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_rules_watchlist_id"),
        "alert_rules",
        ["watchlist_id"],
        unique=False,
    )
    op.create_table(
        "version_ranges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("version_start", sa.String(length=128), nullable=True),
        sa.Column("version_start_including", sa.Boolean(), nullable=False),
        sa.Column("version_end", sa.String(length=128), nullable=True),
        sa.Column("version_end_including", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id",
            "version_start",
            "version_start_including",
            "version_end",
            "version_end_including",
            name="uq_product_version_range",
        ),
    )
    op.create_index(
        op.f("ix_version_ranges_product_id"),
        "version_ranges",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_disagreements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.Column(
            "conflicting_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["vulnerability_source_records.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vulnerability_id",
            "field_name",
            "source_record_id",
            name="uq_vuln_disagreement",
        ),
    )
    op.create_index(
        op.f("ix_vulnerability_disagreements_source_record_id"),
        "vulnerability_disagreements",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_disagreements_vulnerability_id"),
        "vulnerability_disagreements",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_provenance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["vulnerability_source_records.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vulnerability_id", "field_name", name="uq_vuln_provenance_field"
        ),
    )
    op.create_index(
        op.f("ix_vulnerability_provenance_source_record_id"),
        "vulnerability_provenance",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_provenance_vulnerability_id"),
        "vulnerability_provenance",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "watchlist_cves",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "cve_id", name="uq_watchlist_cve"),
    )
    op.create_index(
        op.f("ix_watchlist_cves_cve_id"), "watchlist_cves", ["cve_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_cves_watchlist_id"),
        "watchlist_cves",
        ["watchlist_id"],
        unique=False,
    )
    op.create_table(
        "watchlist_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "product_id", name="uq_watchlist_product"),
    )
    op.create_index(
        op.f("ix_watchlist_products_product_id"),
        "watchlist_products",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watchlist_products_watchlist_id"),
        "watchlist_products",
        ["watchlist_id"],
        unique=False,
    )
    op.create_table(
        "watchlist_vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "vendor_id", name="uq_watchlist_vendor"),
    )
    op.create_index(
        op.f("ix_watchlist_vendors_vendor_id"),
        "watchlist_vendors",
        ["vendor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watchlist_vendors_watchlist_id"),
        "watchlist_vendors",
        ["watchlist_id"],
        unique=False,
    )
    op.create_table(
        "alert_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UNREAD", "READ", "DISMISSED", name="alerteventstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_events_rule_id"), "alert_events", ["rule_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_events_vulnerability_id"),
        "alert_events",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "vulnerability_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("version_range_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_range_id"], ["version_ranges.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"], ["vulnerabilities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vulnerability_id",
            "product_id",
            "version_range_id",
            name="uq_vuln_product_version",
        ),
    )
    op.create_index(
        op.f("ix_vulnerability_products_product_id"),
        "vulnerability_products",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_products_version_range_id"),
        "vulnerability_products",
        ["version_range_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_products_vulnerability_id"),
        "vulnerability_products",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "delivery_method",
            sa.Enum("EMAIL", "WEBHOOK", name="alertaction"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="deliverystatus"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["alert_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_event_id"),
        "notification_deliveries",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_deliveries_event_id"),
        table_name="notification_deliveries",
    )
    op.drop_table("notification_deliveries")
    op.drop_index(
        op.f("ix_vulnerability_products_vulnerability_id"),
        table_name="vulnerability_products",
    )
    op.drop_index(
        op.f("ix_vulnerability_products_version_range_id"),
        table_name="vulnerability_products",
    )
    op.drop_index(
        op.f("ix_vulnerability_products_product_id"),
        table_name="vulnerability_products",
    )
    op.drop_table("vulnerability_products")
    op.drop_index(op.f("ix_alert_events_vulnerability_id"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_rule_id"), table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(
        op.f("ix_watchlist_vendors_watchlist_id"), table_name="watchlist_vendors"
    )
    op.drop_index(
        op.f("ix_watchlist_vendors_vendor_id"), table_name="watchlist_vendors"
    )
    op.drop_table("watchlist_vendors")
    op.drop_index(
        op.f("ix_watchlist_products_watchlist_id"), table_name="watchlist_products"
    )
    op.drop_index(
        op.f("ix_watchlist_products_product_id"), table_name="watchlist_products"
    )
    op.drop_table("watchlist_products")
    op.drop_index(op.f("ix_watchlist_cves_watchlist_id"), table_name="watchlist_cves")
    op.drop_index(op.f("ix_watchlist_cves_cve_id"), table_name="watchlist_cves")
    op.drop_table("watchlist_cves")
    op.drop_index(
        op.f("ix_vulnerability_provenance_vulnerability_id"),
        table_name="vulnerability_provenance",
    )
    op.drop_index(
        op.f("ix_vulnerability_provenance_source_record_id"),
        table_name="vulnerability_provenance",
    )
    op.drop_table("vulnerability_provenance")
    op.drop_index(
        op.f("ix_vulnerability_disagreements_vulnerability_id"),
        table_name="vulnerability_disagreements",
    )
    op.drop_index(
        op.f("ix_vulnerability_disagreements_source_record_id"),
        table_name="vulnerability_disagreements",
    )
    op.drop_table("vulnerability_disagreements")
    op.drop_index(op.f("ix_version_ranges_product_id"), table_name="version_ranges")
    op.drop_table("version_ranges")
    op.drop_index(op.f("ix_alert_rules_watchlist_id"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_user_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_watchlists_user_id"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_index(
        op.f("ix_vulnerability_source_records_vulnerability_id"),
        table_name="vulnerability_source_records",
    )
    op.drop_table("vulnerability_source_records")
    op.drop_index(
        op.f("ix_vulnerability_cwes_vulnerability_id"), table_name="vulnerability_cwes"
    )
    op.drop_index(op.f("ix_vulnerability_cwes_cwe_id"), table_name="vulnerability_cwes")
    op.drop_table("vulnerability_cwes")
    op.drop_index(op.f("ix_products_vendor_id"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_vulnerabilities_cve_id"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_cwes_cwe_id"), table_name="cwes")
    op.drop_table("cwes")
    op.drop_index(
        op.f("ix_connector_states_connector_name"), table_name="connector_states"
    )
    op.drop_table("connector_states")
    # ### end Alembic commands ###
